# Generated by Django 2.2.6 on 2019-10-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20191010_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='location',
            new_name='place',
        ),
    ]
