# Generated by Django 2.2.6 on 2019-10-11 16:35

from django.db import migrations, models
from ..models import Place
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20191010_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
