# Generated by Django 2.2.6 on 2019-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20191011_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='scratched',
            field=models.BooleanField(default=False),
        ),
    ]
