# Generated by Django 2.2.6 on 2019-10-18 16:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_checkin_scratched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='checkin',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
